name: Deploy-compose
on:
  push:
    branches: 
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      -  name: copy file to server
         uses: appleboy/ssh-action@v1.0.3
         with:
           host: ${{ SERVER_HOST.SERVER_HOST }}
           username: ${{ SERVER_HOST.SERVER_USER }}
           key: ${{ SERVER_HOST.SSH_PRIVATE_KEY }}
